// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LACnplzBmAnmeXW1vig807ImsSGmmLo',
    appId: '1:665410992545:web:cf0785a34dc22586a8b3e0',
    messagingSenderId: '665410992545',
    projectId: 'fir-firebase-setup-cc311',
    authDomain: 'fir-firebase-setup-cc311.firebaseapp.com',
    storageBucket: 'fir-firebase-setup-cc311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARfbu2Bx4OYrez-46SA2J-IQ-1bvwYdZc',
    appId: '1:665410992545:android:4395f1b1e731043ba8b3e0',
    messagingSenderId: '665410992545',
    projectId: 'fir-firebase-setup-cc311',
    storageBucket: 'fir-firebase-setup-cc311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZwL_-1P9BnlK_3azIpAVIBxL-Bv3s9M',
    appId: '1:665410992545:ios:aac3772c2652d7f8a8b3e0',
    messagingSenderId: '665410992545',
    projectId: 'fir-firebase-setup-cc311',
    storageBucket: 'fir-firebase-setup-cc311.appspot.com',
    iosClientId: '665410992545-0ms3n1gfoqkn04rsg8hrhkc5j3su9e1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZwL_-1P9BnlK_3azIpAVIBxL-Bv3s9M',
    appId: '1:665410992545:ios:aac3772c2652d7f8a8b3e0',
    messagingSenderId: '665410992545',
    projectId: 'fir-firebase-setup-cc311',
    storageBucket: 'fir-firebase-setup-cc311.appspot.com',
    iosClientId: '665410992545-0ms3n1gfoqkn04rsg8hrhkc5j3su9e1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebaseSetup',
  );
}
